apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: argo
type: Opaque
stringData:
  SPELLCHECK_API_KEY: "https://spellcheck.lifebookshelf.org"
  QUESTION_API_URL: "https://ai.lifebookshelf.org"
  PUBLISH_API_TOKEN: "https://publish.lifebookshelf.org"
  MAIN_API_TOKEN: "https://api.lifebookshelf.org"