apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: autobiography-pipeline-
spec:
  entrypoint: main
  serviceAccountName: argo
  templates:
    - name: main
      dag:
        tasks:
          - name: iot-input
            templateRef:
              name: api-call-templates
              template: call-iot-api

          - name: emotion-recog
            dependencies: [iot-input]
            templateRef:
              name: api-call-templates
              template: call-emotion-api

          - name: rcmd-question
            dependencies: [iot-input]
            templateRef:
              name: api-call-templates
              template: call-question-api

          - name: receive-answer
            dependencies: [rcmd-question]
            templateRef:
              name: container-templates
              template: receive-answer

          - name: generate-autobio
            dependencies: [emotion-recog, receive-answer]
            templateRef:
              name: container-templates
              template: generate-autobio

          - name: merge-autobio
            dependencies: [generate-autobio]
            templateRef:
              name: container-templates
              template: merge-autobio

          - name: spell-check
            dependencies: [merge-autobio]
            templateRef:
              name: api-call-templates
              template: call-spellcheck-api

          - name: publication
            dependencies: [spell-check]
            templateRef:
              name: api-call-templates
              template: call-publish-api
